### ISSUE TITLE
simulation_util

### ISSUE THREAD

**Issue by HRSAstro** [lenstronomy/lenstronomy-tutorials#1]
Hi Simon,

I am playing around using your example quad model. The first thing this does is create a mock dataset, however lenstronomy.Util.simulation_util does not exist in the installed package nor anywhere in the documentation. Has this not been implemented yet?

Cheers,
Hannah

**Comment by sibirrer** [comment]
Hi Hannah,

The notebooks should follow always the latest PyPi release version, in the current case 0.6.0. This should allow you to use it. Here is the master branch version with the same routines:
https://github.com/sibirrer/lenstronomy/blob/master/lenstronomy/Util/simulation_util.py

Let me know in case it does not help or if you have other questions! 
We have also a google group where I announce new releases etc. https://groups.google.com/forum/#!forum/lenstronomy

Cheers,
Simon

**Comment by HRSAstro** [comment]
Hi Simon,

Yes, it seems I had version 0.5.0 that was the problem.

Cheers,
Hannah

**Comment by sibirrer** [comment]
ok, great. I close the issue then
