### ISSUE TITLE
Colab link for notebooks

### ISSUE THREAD

**Issue by sibirrer** [lenstronomy/lenstronomy-tutorials#12]
direct links to google colab or any other free online Jupyter server could enhance the visibility and usability of the notebooks without the need to download them and having lenstronomy installed locally.
What we would need to change in all the notebooks is that the installation of lenstronomy (and potentially other software) need to be done in the notebook itself with
>>> !pip install lenstronomy

One way to not double install lenstronomy if operated in the current form is to have a condition:
>>> try:
>>>    import lenstronomy
>>> except:
>>>   !pip install lenstronomy

**Comment by ajshajib** [comment]
I think, Google colab had trouble installing fastell4py last time I tried it. So, notebooks using `'PEMD'` mass profile would need to change to `'EPL'` mass profile, just a heads up.

**Comment by ajshajib** [comment]
Closing this issue, since it is taken care of with PR #13.
