### ISSUE TITLE
No module named 'lenstronomy.LensModel.Util.decouple_multi_plane_util

### ISSUE THREAD

**Issue by King-of-being** [lenstronomy/lenstronomy-tutorials#24]
At "from lenstronomy.LensModel.Util.decouple_multi_plane_util import *" in the modeling_with_decoupled_multiplane.ipynb, ERROR RAISED:"No module named 'lenstronomy.LensModel.Util.decouple_multi_plane_util'", Could you help me with it?

**Comment by sibirrer** [comment]
I'll tag @dangilman

**Comment by King-of-being** [comment]
thank you very much! Hope your work goes fine!!

> I'll tag @dangilman

**Comment by King-of-being** [comment]
> I'll tag @dangilman

Hello? May I know is there any reply?
