### ISSUE TITLE
KeyError: 'e1'

### ISSUE THREAD

**Issue by jun01ee** [lenstronomy/lenstronomy-tutorials#3]
I am trying to test with an elliptical-NFW and shear lens as follows. The initial error was `KeyError: 'alpha_Rs'` when I used `'theta_Rs'` instead of `'alpha_Rs'`. After I change the key in the dictionary `kwargs_lens_init`, the error became `KeyError: 'e1'`.
The same error occurs if I change `'gamma1'` and `'gamma2'` to `'e1'` and `'e2'` respectively.
I believe it may be some mistake of parameter naming? Can someone point it out if otherwise?

![image](https://user-images.githubusercontent.com/56535319/97551782-5bfb6b00-1a0e-11eb-8af2-e669f2024973.png)
![image](https://user-images.githubusercontent.com/56535319/97551866-79303980-1a0e-11eb-839c-3b2fdab967b5.png)

 ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-48-02b9d4955579> in <module>
      6 
      7 start_time = time.time()
----> 8 chain_list_pso = fitting_seq.fit_sequence(fitting_kwargs_list)
      9 kwargs_result = fitting_seq.best_fit()
     10 end_time = time.time()

~\AppData\Roaming\Python\Python38\site-packages\lenstronomy\Workflow\fitting_sequence.py in fit_sequence(self, fitting_list)
     78 
     79             elif fitting_type == 'PSO':
---> 80                 kwargs_result, chain, param = self.pso(**kwargs)
     81                 self._updateManager.update_param_state(**kwargs_result)
     82                 chain_list.append([fitting_type, chain, param])

~\AppData\Roaming\Python\Python38\site-packages\lenstronomy\Workflow\fitting_sequence.py in pso(self, n_particles, n_iterations, sigma_scale, print_key, threadCount)
    250         param_class = self.param_class
    251         kwargs_temp = self._updateManager.parameter_state
--> 252         init_pos = param_class.kwargs2args(**kwargs_temp)
    253         kwargs_sigma = self._updateManager.sigma_kwargs
    254         sigma_start = param_class.kwargs2args(**kwargs_sigma)

~\AppData\Roaming\Python\Python38\site-packages\lenstronomy\Sampling\parameters.py in kwargs2args(self, kwargs_lens, kwargs_source, kwargs_lens_light, kwargs_ps, kwargs_special, kwargs_extinction)
    312         """
    313 
--> 314         args = self.lensParams.setParams(kwargs_lens)
    315         args += self.souceParams.setParams(kwargs_source)
    316         args += self.lensLightParams.setParams(kwargs_lens_light)

~\AppData\Roaming\Python\Python38\site-packages\lenstronomy\LensModel\lens_param.py in setParams(self, kwargs_list)
    115                     #        pass
    116                     else:
--> 117                         args.append(kwargs[name])
    118         return args
    119 

KeyError: 'e1'

**Comment by sibirrer** [comment]
Hi @jun01ee, the ellipticity convention in lenstronomy is using the eccentricity moduli 'e1' and 'e2' rather than an angle and axis ratio. These conventions have been changed a while back. If you want to turn your axis ratio into eccentricities, you can do so. Check out e.g. this notebook: https://github.com/sibirrer/lenstronomy_extensions/blob/master/lenstronomy_extensions/Notebooks/units_coordinates_parameters.ipynb

**Comment by jun01ee** [comment]
@sibirrer Thanks for your comment. I followed the naming in the source code here, are these older version? Since `'theta_Rs'`, `'phi_G'` and `'q'` are used. [https://lenstronomy.readthedocs.io/en/stable/lenstronomy.LensModel.Profiles.html#module-lenstronomy.LensModel.Profiles.nfw](url)

**Comment by sibirrer** [comment]
hmm...seems the readthedocs with 'stable' is outdated. If you go to 'latest' you'll find the up-to-date documentation.
https://lenstronomy.readthedocs.io/en/latest/lenstronomy.LensModel.Profiles.html#module-lenstronomy.LensModel.Profiles.nfw

I guess I need to fix 'stable' to change to the latest version.

**Comment by jun01ee** [comment]
I see. Great thanks! I will try again.
